[package]
name = "aoc2021"
description = "Solutions for Advent of code 2021"
version = "1.0.0"
edition = "2021"
authors = ["Neffarion"]

[dependencies]
phf = { version = "^0", features = ["macros"] }
derive_more = { version = "^0" }